In [430]:
import numpy as np
import pandas as pd
from scipy import linalg
import scipy
a = [np.random.randint(1,100,50) for i in range(5)]

In [431]:
a = np.matrix(a)
a.shape

(5, 50)

In [447]:

a = np.matrix(a)
K = 4
#mean normalization
am = np.zeros(shape=a.shape)
for i in range(a.shape[1]):
    for j in range(a.shape[0]):
        am[j,i] = a[j,i] - np.mean(a[:,i])
    
# from sklearn.preprocessing import scale
# X = scale( X, axis=0, with_mean=True, with_std=True, copy=True )

cov = np.dot(np.transpose(am),am)*(1/am.shape[0])
U, s, Vh = linalg.svd(cov)

In [448]:
z= np.zeros(shape=(am.shape[0],K))
U = np.matrix(U)

for j in range(K):
    for i in range(am.shape[0]):
        z[i,j] = np.transpose(am[i,:]) * U[:,j]
      
print(z)

z = np.matrix(z)
U = np.matrix(U)
U


[[-143.57311015 -103.27468915  -56.0152188   -38.10453891]
 [ -41.61334067  151.77518672  -67.86838234   36.2141582 ]
 [ 137.22949989    8.93724784  -10.97773705 -105.97942843]
 [ -54.78247049   24.35806888  147.38024984    3.19176511]
 [ 102.73942142  -81.79581429  -12.51891166  104.67804403]]


matrix([[-0.13327702,  0.03251613, -0.09276836, ..., -0.00389514,
          0.02193321,  0.80011362],
        [ 0.1343441 , -0.2099348 , -0.03568302, ...,  0.00664687,
          0.03836401, -0.0818934 ],
        [ 0.06229305, -0.12395809, -0.10408374, ..., -0.00198485,
          0.05751273,  0.07074936],
        ..., 
        [-0.09349267, -0.00086439,  0.09520929, ..., -0.24418511,
         -0.14083558, -0.02351203],
        [ 0.20666492,  0.10960082, -0.12590082, ..., -0.03697618,
          0.13432417,  0.03787429],
        [-0.09819181, -0.02695098,  0.12488209, ...,  0.1040469 ,
          0.05388725, -0.03332193]])

In [449]:
#recover
ax = np.zeros(shape=a.shape)
for i in range(z.shape[0]):
    for j in range(U.shape[0]):
        ax[i,j] = z[i,:] * np.transpose(U[j,0:K])
print(ax)
print(am)

[[  2.60000000e+01   5.20000000e+00   1.48000000e+01   3.36000000e+01
   -5.40000000e+00   4.20000000e+00   6.18000000e+01   4.98000000e+01
    1.00000000e+00  -1.74000000e+01   4.10000000e+01  -1.32000000e+01
    5.16000000e+01  -1.02000000e+01   4.68000000e+01  -1.80000000e+00
   -2.92000000e+01   1.08000000e+01  -1.32000000e+01  -2.44000000e+01
    4.98000000e+01   1.08000000e+01   4.56000000e+01  -9.60000000e+00
   -4.56000000e+01  -5.20000000e+00   4.34000000e+01  -2.54000000e+01
    3.58000000e+01  -1.18000000e+01  -2.80000000e+00   3.60000000e+00
    5.80000000e+00   3.72000000e+01  -2.10000000e+01   1.16000000e+01
   -8.40000000e+00  -9.60000000e+00   1.20000000e+01   8.80000000e+00
   -7.20000000e+00   1.22000000e+01  -1.46000000e+01  -2.00000000e+01
   -3.00000000e+01   3.02000000e+01   3.26000000e+01   2.60000000e+00
   -3.88000000e+01   1.38000000e+01]
 [  1.20000000e+01  -3.58000000e+01  -1.92000000e+01  -7.40000000e+00
    1.76000000e+01  -6.08000000e+01  -1.82000000e+01 

In [450]:
#average squared projection error
sqp = (1/am.shape[0]) * sum(np.linalg.norm(am - ax ,axis=0)**2)    
sqp

8.151962869847167e-27

In [451]:
#Total variation in the data
TV = (1/am.shape[0]) * sum(np.linalg.norm(am,axis=0)**2)    
TV

30100.640000000003

In [452]:
#ratio of sqp and TV should be less than or equal to 0.01 to keep the 99 percent variance.
sqp/TV

2.7082357284918746e-31

In [453]:
# to check the variance in a simple way use the sum of s value from the SVD 
#and take first k number of s devide it by all sum of s it should be greater than or equal to 0.99
sum(s[0:K])/sum(s)

1.0

In [454]:
# PCA using sikitlearn.
from sklearn.decomposition import PCA
pca = PCA(n_components=K)
pca.fit(a)

print(pca.transform(a))
print(pca.explained_variance_ratio_) 
print(pca.explained_variance_)
print(pca.singular_values_)
print(pca.components_)
pca_score = pca.explained_variance_ratio_
V = pca.components_

[[ 143.57311015 -103.27468915  -56.0152188    38.10453891]
 [  41.61334067  151.77518672  -67.86838234  -36.2141582 ]
 [-137.22949989    8.93724784  -10.97773705  105.97942843]
 [  54.78247049   24.35806888  147.38024984   -3.19176511]
 [-102.73942142  -81.79581429  -12.51891166 -104.67804403]]
[ 0.36366902  0.2728521   0.19761702  0.16586186]
[ 13683.33787665  10266.27846894   7435.49849021   6240.6851642 ]
[ 233.95160078  202.64529078  172.4586732   157.99601469]
[[ 0.13327702 -0.1343441  -0.06229305  0.13547566  0.00537923 -0.10081394
   0.21294171  0.07631596 -0.02676333 -0.2020138   0.04742523 -0.12330423
   0.22561599 -0.1394657   0.23464708  0.05750109 -0.28586159  0.15877868
   0.080884   -0.19984848  0.04726082 -0.05279474  0.25663271 -0.0454966
  -0.21974106 -0.0282227   0.26285947 -0.04817391  0.10368747 -0.02404903
  -0.14722559  0.14120187 -0.00123846  0.18807333 -0.11199997 -0.07352326
  -0.0872359  -0.17648161  0.19662621  0.10849384  0.01307451  0.08836952
   0.04314575

In [455]:
Y = np.cov(a,rowvar=False,bias=False,ddof=0)
U1, pca_score, V = scipy.linalg.svd(Y, full_matrices=False)

In [456]:
cov

array([[ 341.2 , -218.4 ,   21.8 , ...,  -12.8 , -286.8 ,  134.8 ],
       [-218.4 ,  569.36,  341.64, ..., -171.72,  128.16, -113.56],
       [  21.8 ,  341.64,  322.96, ..., -219.88,   21.84,  -48.04],
       ..., 
       [ -12.8 , -171.72, -219.88, ...,  256.64, -190.32,   96.32],
       [-286.8 ,  128.16,   21.84, ..., -190.32,  741.76, -405.36],
       [ 134.8 , -113.56,  -48.04, ...,   96.32, -405.36,  256.96]])

In [457]:
Y

array([[ 341.2 , -218.4 ,   21.8 , ...,  -12.8 , -286.8 ,  134.8 ],
       [-218.4 ,  569.36,  341.64, ..., -171.72,  128.16, -113.56],
       [  21.8 ,  341.64,  322.96, ..., -219.88,   21.84,  -48.04],
       ..., 
       [ -12.8 , -171.72, -219.88, ...,  256.64, -190.32,   96.32],
       [-286.8 ,  128.16,   21.84, ..., -190.32,  741.76, -405.36],
       [ 134.8 , -113.56,  -48.04, ...,   96.32, -405.36,  256.96]])

In [458]:
U1

array([[-0.13327702,  0.03251613, -0.09276836, ..., -0.00389514,
         0.02193321,  0.80011362],
       [ 0.1343441 , -0.2099348 , -0.03568302, ...,  0.00664687,
         0.03836401, -0.0818934 ],
       [ 0.06229305, -0.12395809, -0.10408374, ..., -0.00198485,
         0.05751273,  0.07074936],
       ..., 
       [-0.09349267, -0.00086439,  0.09520929, ..., -0.24418511,
        -0.14083558, -0.02351203],
       [ 0.20666492,  0.10960082, -0.12590082, ..., -0.03697618,
         0.13432417,  0.03787429],
       [-0.09819181, -0.02695098,  0.12488209, ...,  0.1040469 ,
         0.05388725, -0.03332193]])